### ISSUE TITLE
Check whether inputted text is correct.

### ISSUE THREAD

**Issue by katchu11** [nasa/PeTaL#13]
Based on the fields that are to be populated, a content extractor (perhaps from AllenNLP) would be used to generate a score of whether the inputted answer is correct with regards to the text and the previous answers that are in the system.

**Comment by pjuangph** [comment]
I don't know if I set the correct milestone. Let me know if I'm wrong or you see that it should be set somewhere else.

**Comment by katchu11** [comment]
Yep this is the right milestone thanks!
