### ISSUE TITLE
Dockerize PeTaL Completely

### ISSUE THREAD

**Issue by LSaldyt** [nasa/PeTaL#17]
Containerize PeTaL into a single startup script, i.e. using docker-compose to spin up the neo4j server and potentially also to pre-fill the database before starting the Django site.

**Comment by pjuangph** [comment]
This might be a problem because of COVID and the interns are far away + Paht doesn't have admin on all their machines. Unless...... IT will install and configure docker.

**Comment by LSaldyt** [comment]
In the absence of docker, it might be helpful to make a top-level script or something that sets up everything (i.e. populates the database and creates the search index before starting the website)

**Comment by bruffridge** [comment]
Docker configuration is working in the develop branch. https://github.com/nasa/PeTaL/tree/develop
