### ISSUE TITLE
Migrate Kunle's RESTful API and Elastic search tool

### ISSUE THREAD

**Issue by pjuangph** [nasa/PeTaL#19]
Pull Kunle's branch of petal https://github.com/kakinpe1u/PeTaL/tree/feature_elasticsearch 
and https://github.com/kakinpe1u/PeTaL/tree/feature_indexer 

Try to see how we can integrate Kunle's elastic search with Petal. 
If we can't integrate then we need to know.
This needs to be done ASAP.

**Comment by keikojima02** [comment]
**This cannot be integrated due to dependency issues!**

Neomodel only supports neo4j versions 3.0, 3.1, 3.2, 3.3

**Comment by keikojima02** [comment]
See branch `elastic_search` for current PeTaL elastic search code. See elastic search wiki for more info. 

Hint. It is not much.
