### ISSUE TITLE
FileNotFoundError ../data/index

### ISSUE THREAD

**Issue by bruffridge** [nasa/PeTaL#28]
Anyone else getting this error when starting up the Django web server? I don't see a data/index file in the repo anywhere, am I supposed to generate this file somehow?

https://github.com/nasa/PeTaL/blob/13d280b79343d1858cddef13391c74e88a13025b/site/bird/search.py#L25

**Comment by pjuangph** [comment]
is this from Kunle's code?

**Comment by LSaldyt** [comment]
The index needs to be created by running the `search` config in the backend, after populating the database with articles. Maybe an error message could be added if this is missing.

**Comment by LSaldyt** [comment]
Also, this is in the second code-block of the [README](https://github.com/nasa/PeTaL/blob/master/README.md), the notes around it might help.

**Comment by pjuangph** [comment]
I don't see any code that creates data/index. I ran search.json for a few hours and data/index was not created. Any ideas where it might be hanging up?

**Comment by LSaldyt** [comment]
Did you fill the database with articles first? [InvertedIndexCreator.py](https://github.com/nasa/PeTaL/blob/master/modules/search/InvertedIndexCreator.py), referenced in `search.json`, creates the index.

Cheers,

- Lucas

**Comment by bruffridge** [comment]
Got this to work in 'develop' branch. Had to run `./run config/search.json` as mentioned, then had to change path to `data/index`.
