### ISSUE TITLE
AttributeError: 'Result' object has no attribute 'records'

### ISSUE THREAD

**Issue by keikojima02** [nasa/PeTaL#29]
Hey Lucas,

Hate to ask you another question, but am I possibly missing some code or data here? I ran 
```
./run config/mock_species_articles.json
```
and then after checking that the database actually had data in it. I ran
```
./run config/search.json
```
to create the index file. I got this error message
```
AttributeError: 'Result' object has no attribute 'records'
```
Documentation about the error message is attached! I really appreciate your time if you could help me with this!
[AttributeError 'Result'object has no attribute 'records'.pdf](https://github.com/nasa/PeTaL/files/4828064/AttributeError.Result.object.has.no.attribute.records.pdf)

**Comment by LSaldyt** [comment]
Weird. `.records()` is a builtin `neo4j` function, it's how the `neo4j` API returns data from a query. Can you post your package versions? Mine are the following:

neo4j==1.7.6
neobolt==1.7.17
neotime==1.7.4

**Comment by LSaldyt** [comment]
Looked into it, and the issue is just that the `neo4j` client version isn't pinned. Either you can remove the `.records()` everywhere, or downgrade `neo4j`. I recommend updating it if possible.
[See this documentation](https://neo4j.com/docs/api/python-driver/current/)

**Comment by LSaldyt** [comment]
See the latest version of bitflow and #30. Does this fix things? The latest `neo4j` client has a ton of breaking changes, and the `requirements.txt` wasn't frozen, so you must've been using `4.0`

**Comment by keikojima02** [comment]
Yes, the poetry package manager did fix the issue! Thank you for all your help.
