### ISSUE TITLE
Store results in neo4j

### ISSUE THREAD

**Issue by CkUnsworth** [nasa/PeTaL#37]
- [ ] Assign Elliot

**Comment by pjuangph** [comment]
What kind of results do you intend to store?

**Comment by CkUnsworth** [comment]
Paht, do you know Elliot's @? I can't find him to tag him or assign him to this task.

**Comment by Elliot-D-Hill** [comment]
This could be my misunderstanding of how neo4j is being used in petal, but I thought that the results from a particular image (taxonomy classification, objects, patterns, etc.) would be stored in the neo4j database where they could later be used for future data mining purposes. If this isn't part of petal's intended functionality I can remove this issue.

**Comment by LSaldyt** [comment]
Right now the machine learning models are being trained on labelled data, so putting their results in neo4j doesn't really make sense (they will already be there). A scenario that would make sense is if you were running a pre-trained model on unlabelled data.

**Comment by Elliot-D-Hill** [comment]
Is the following the intended functionality for the computer vision tool?

1. Neural net trained/validated/tested on labeled images in neo4j database.
2. Neural net inference performed on user-provided unlabeled images

It was this user-provided unlabeled data that I had imagined being stored in the database after classification (for future model training or data mining). Though, this could raise data integrity issues. I'm still getting familiarized with petal, so let me know if I am thinking about this the wrong way.
