### ISSUE TITLE
ModuleNotFoundError: No module named 'modules.mock.EOLSpeciesModule'

### ISSUE THREAD

**Issue by bruffridge** [nasa/PeTaL#38]
Get an error when running this:
./run config/mock_species_articles.json

**Comment by keikojima02** [comment]
Has this been resolved, or is this still an issue?

**Comment by pjuangph** [comment]
Still an issue. I fixed it in bitflow on Alex's computer but didn't push the change. Line 19 should be something like == instead of "in" and filename should be filename.replace('.py','') https://github.com/LSaldyt/bitflow/blob/master/bitflow/utils/utils.py

**Comment by keikojima02** [comment]
It seems like a problem specific to macs, because I ran into it on Elliot's computer.
