### ISSUE TITLE
Add Computer Vision Tool

### ISSUE THREAD

**Issue by pjuangph** [nasa/PeTaL#40]
Add Maju's segmentatioin work. Vik or Paht can send you the files

**Comment by LSaldyt** [comment]
Manju's code is also in `/legacy/`

**Comment by keikojima02** [comment]
Will the updates @Elliot-D-Hill will be working on (like Issue #33) effect this issue?

**Comment by keikojima02** [comment]
UI has been moved from Flask to Django. But due to possible issues in Manju's code and the new version of vision @Elliot-D-Hill is working on, this will be put on hold.

**Comment by keikojima02** [comment]
This issue is completed in commit 59c5456269d599d650629eee0a37a5ced8c199a0 for the now.
