### ISSUE TITLE
Add NLP Connor's work

### ISSUE THREAD

**Issue by pjuangph** [nasa/PeTaL#41]
Vik and PAht has the files

**Comment by LSaldyt** [comment]
`/legacy/` directory?

**Comment by pjuangph** [comment]
I think it's in vik's onedrive.

**Comment by keikojima02** [comment]
I believe Kashyap is working on a new NLP. What do we plan doing with Connor's code? Also, is this referring to SEALs as well?

**Comment by keikojima02** [comment]
Closed in pull request #69
