### ISSUE TITLE
Add ability to read neo4j connection information from config file

### ISSUE THREAD

**Issue by pjuangph** [nasa/PeTaL#48]
Different files inside module/* have manually (in the python code) entered connection strings. We need to change this so that it uses the same configuration file (json)

Example files:
site/search/bird.py 
modules/libraries/download_wikipedia/wiki_to_neo.py 

There may be other files that need updating.

**Comment by keikojima02** [comment]
This issue is fixed in commit 5dc4cb079ea5a06630728f2665a76a9f7756138e
