### ISSUE TITLE
Enable Inputs Through PeTaL UI: Connect BIRD dropdowns to neo4j data

### ISSUE THREAD

**Issue by keikojima02** [nasa/PeTaL#58]
### Summary of Issue
BIRD dropdown menu lists will be populated with relevant Neo4j data.
### Issue Type
Enhancement

### Description
Three dropdown menu's should be created. Functions, Species, Environment.

### Example
Here is a [link ](http://www.catalogueoflife.org/DCA_Export/) as an example end product for the species dropdowns.

**Comment by CkUnsworth** [comment]
I might call the third dropdown "Environment" instead of habitat, as habitat is something a little more specific. Unless there is a reason for using that term instead?

**Comment by keikojima02** [comment]
Will name it environment. There was not a reason. Thank you for the input!

**Comment by keikojima02** [comment]
May be putting this issue on hold due to the data structure in neo4j is not completely defined.
